bank_aliases:
  湖南三湘银行: [三湘银行, 三湘]
  长沙银行: [长沙银行]
  上饶银行: [上饶银行]
  江西银行: [江西银行]
  江西农商银行: [江西·农商银行, 江西农商银行, 江西农商]
  宜春农村商业银行: [宜春农村商业银行股份有限公司, 宜春农村商业银行, 宜春农商银行]
  上饶农村商业银行: [上饶农村商业银行股份有限公司, 上饶农村商业银行, 上饶农商银行]
  中国邮政储蓄银行: [中国邮政储蓄银行, 邮政储蓄银行, 邮政储蓄, 邮储银行, 邮储]
  农村商业银行: [农村商业银行, 农商银行, 农商行]
  农村信用社: [农村信用社, 农村信用, 农信社, 信用社, 农村合作银行]
  村镇银行: [村镇银行]
  上海浦东发展银行: [上海浦东发展银行, 浦东发展银行, 浦发银行, 浦发]
  中国工商银行: [中国工商银行, 工商银行, 工行]
  中国农业银行: [中国农业银行, 农业银行, 农行]
  中国建设银行: [中国建设银行, 建设银行, 建行]
  交通银行: [交通银行, 交行]
  中国银行: [中国银行, 中行]
  招商银行: [招商银行, 招行]
  中信银行: [中信银行, 中信]
  中国民生银行: [中国民生银行, 民生银行, 民生]
  兴业银行: [兴业银行, 兴业]
  中国光大银行: [中国光大银行, 光大银行, 光大]
  平安银行: [平安银行]
  广发银行: [广发银行, 广发]
  华夏银行: [华夏银行, 华夏]
  北京银行: [北京银行]
  上海银行: [上海银行]
  南京银行: [南京银行]
  宁波银行: [宁波银行]
  杭州银行: [杭州银行]
